version: '3'

services:
  bot:
    container_name: lms-scraper
    build:
      context: ./
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./assets:/app/assets
      - ./data:/app/data
      - ./output:/app/output
    restart: always
